CREATE DATABASE PROJETO;

USE PROJETO;

CREATE TABLE CURSOS(
    IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    HORAS INT NOT NULL,
    VALOR FLOAT(10,2) NOT NULL
);

INSERT INTO CURSOS VALUE(NULL, 'C# Para iniciantes', 78, 32.20);
INSERT INTO CURSOS VALUE(NULL, 'JAVA', 30,500.00)
INSERT INTO CURSOS VALUE(NULL, 'FUNDAMENTOS DE BANCO DE DADOS', 40, 700.20);

SELECT * FROM CURSOS;

DELIMITER $

STATUS

CREATE PROCEDURE CAD_CURSO(P_NOMP_NOME VARCHAR(30),
                           P_HORAS INT,
                           P_VALOR FLOAT(10,2));
BEGIN
    INSERT INTO CURSOS VALUE(NULL, P_NOME, P_HORAS, P_VALOR);
END
$

CREATE PROCEDURE GET_CURSOS()
BEGIN
    SELECT * FROM CURSOS;
END
$

DELIMITER ;

CALL CAD_CURSO('BI SQL SERVER', 35, 3000.23);
CALL CAD_CURSO('POWER BI', 20, 1000.33);
CALL CAD_CURSO('TABLEAU', 30, 1200.99);
CALL CAD_CURSO('MARKETING DIGITAL', 15, 5000.00);
CALL CAD_CURSO('JAVASCRIPT ZERO TO HERO', 92, 399.99);
CALL CAD_CURSO('REACTJS', 35, 700.00);