CREATE TABLE TABELA(
    COLUNA1 VARCHAR(30),
    COLUNA2 VARCHAR(30),
    COLULA3 VARCHAR(30)
);

ALTER TABLE TABELA
ADD PRIMARY KEY (COLUNA1);

DESC TABELA;

ALTER TABLE TABELA
ADD COLUNA VARCHAR(30);

ALTER TABLE TABELA
ADD COLUNA100 int;

ALTER TABLE TABELA
ADD COLUMN COlUNA4 VARCHAR(30) NOT NULL UNIQUE
AFTER COLULA3;

ALTER TABLE TABELA
CHANGE colula3 COLUNA3 VARCHAR(30);

ALTER TABLE TABELA
MODIFY COLUNA2 DATE NOT NULL;

ALTER TABLE TABELA
RENAME PESSOA;

CREATE TABLE TIME(
    IDTIME INT PRIMARY KEY AUTO_INCREMENT,
    TIME VARCHAR(30),
    ID_PESSOA VARCHAR(30)
);

ALTER TABLE TIME
ADD FOREIGN KEY(ID_PESSOA)
REFERENCES PESSOA(COLUNA1);